#![recursion_limit = "256"]

pub mod actions;
pub mod app;
pub mod audio_webview;
pub mod board;
pub mod board_index;
pub mod input;
pub mod landing;
pub mod loading;
pub mod markdown_card;
pub mod notifications;
pub mod pdf_thumbnail;
pub mod pdf_webview;
pub mod render;
pub mod settings;
pub mod spotify_webview;
pub mod types;
pub mod video_webview;
pub mod youtube_webview;
